name: Intro to CI/CD

on: [push, pull_request]

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v2
            - name: hello world
              run: echo "Hello world"
            - name: install python ver 3.9
              uses: actions/checkout@v2
              with:
                python-version: "3.9"
            - name: update pip
              run: python -m pip install --upgrade pip
            - name: install all dependencies
              run: pip install -r requirements.txt
            - name: Run pytest
              run:
                pip install pytest
                pytest -v -s



